# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  name: Hosted macOS
  demands:
    - java
    - JDK

steps:
- script: echo Hello, world new!
  displayName: 'Run a one-line script'

- bash: |
    Hours=`date '+%H'`
    echo $Hours
    echo $date

- task: Gradle@2
  displayName: 'Build Release APK'
  inputs:
    gradleWrapperFile: gradlew
    tasks: assembleRelease
